builds:
  - main: .
    binary: brus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - balls
      - docs
      - Merge pull request
      - Merge branch
      - Releasing v
      - lulz

archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
      - LICENSE
      - README.md
